### ISSUE TITLE
Environment setup should be executed within singularity containers?

### ISSUE THREAD

**Issue by mseitzer** [martius-lab/cluster_utils#68]
The current implementation of using singularity containers performs the environment setup outside of the container. I think in most cases, the environment would be installed within the container, and so the environment setup (e.g. `source venv/bin/activate`) needs to happen inside the container, before the main script is executed.

I don't know how to best implement this. Maybe this also should to be left to the user, because there are many different things people could do? Although I think it would be great if cluster_utils offers a standard solution for that problem.

The same problem occurs for `pre_job_script` and `variables`. These should probably also act *within* the container.

**Comment by luator** [comment]
The discussion here is now covering multiple actual tasks.  To keep overview, I created separate issues for them (see reference links above) and will close this one.
