### ISSUE TITLE
Report build fails on Galvani

### ISSUE THREAD

**Issue by luator** [martius-lab/cluster_utils#72]
Generating the report at the end of a grid search fails on Galvani with this error:

> ! LaTeX Error: File `framed.sty' not found.

I assume the corresponding package is simply not installed there.

Not sure what's the best solution to this.  One option could be to provide a container which contains all packages needed for the report.  This would make us independent on what is provided on the cluster but the user would somehow need to download that container, which could be a bit annoying.  Maybe it could happen automatically during the installation of cluster_utils.

**Comment by luator** [comment]
I realised that using a container to run the cluster_utils main process doesn't work so easily as it can't submit jobs from inside the container.  At least unless I install the Slurm stuff in the container as well, which doesn't seem practical.
In this case, there is another rather simple solution, though: I build a container with only pdflatex (see below), named the file `pdflatex` and put it in the PATH.  So basically this works as a standalone executable to run pdflatex.

```singularity
bootstrap: docker
from: ubuntu:22.04

%post
    set -e
    export DEBIAN_FRONTEND=noninteractive

    echo "deb http://us.archive.ubuntu.com/ubuntu focal universe" >> /etc/apt/sources.list
    apt-get update
    apt-get install -y texlive-latex-base texlive-latex-extra

    # cleanup to reduce container size
    apt-get clean

%runscript
    pdflatex "$@"
```

I'll put that somewhere in the documentation and then I think this issue can be closed.

**Comment by mseitzer** [comment]
That sounds great for solving the latex issue, although I think the question of how to provide a standalone cluster_utils is still relevant. Is it possible to mount the host binaries into the container and link them?

**Comment by mseitzer** [comment]
In that case, binding `sbatch` should be sufficient, I guess.

**Comment by luator** [comment]
I think you can only bind directories, not individual files, so not sure if that would easily work.  Do we actually have a use case where a container for running the cluster_utils main process is really needed?  If yes, we should track it in a dedicated issue.

**Comment by mseitzer** [comment]
I just checked, you can indeed bind files. The use case is that everyone can pull the latest container (automatically built) from Github, and does not need to install cluster utils anymore. Seems convenient to me.
