### ISSUE TITLE
Cannot use pyuv as is on PyPI

### ISSUE THREAD

**Issue by luator** [martius-lab/cluster_utils#80]
Currently we depend on the master-branch version of pyuv as it contains unreleased fixes for recent Python versions.
Since PyPI doesn't allow dependencies on external sources, this is blocking us from publishing cluster_utils there.

pyuv does not seem to be actively worked on anymore, so it's a bit unclear if a new release will happen any time soon (the maintainer is still around, though, see [related issue](https://www.github.com/saghul/pyuv/issues/276)).

So until a new release of pyuv happens, I see the following potential workarounds

1. Add pyuv as subpackage to cluster_utils, so we don't have an external dependency on it.  Not sure how much this would complicate the build process.
2. Fork pyuv and put our fork on PyPI. I'm not a big fan of that, though, as it pollutes PyPI with temporary workaround packages.
3. Find an alternative to pyuv which is more actively maintained.  At least during some quick research I didn't find an obvious replacement, though.

**Comment by luator** [comment]
Actually, getting a new official release might not be that far away, see latest comments on the issue linked above :).

**Comment by mseitzer** [comment]
Thanks for asking them! Let's hope pyuv gets a new release, as replacing it will not be trivial. 

An alternative could be the Python asyncio event loop, or its faster implementation, [uvloop](https://github.com/MagicStack/uvloop). However, I think those are missing some components we would need (e.g. a UDP implementation).

**Comment by mseitzer** [comment]
Okay, sounds promising. With network communication, the devil is always in the detail though..
