### ISSUE TITLE
Get rid of git-dependency on smart_settings

### ISSUE THREAD

**Issue by luator** [martius-lab/cluster_utils#81]
For smart_settings, we currently depend on `git+https://github.com/martius-lab/smart-settings.git`.  Dependencies on external sources are not allowed for packages on PyPI so this is blocking us from publishing cluster_utils there.

So we either need to publish smart_settings on PyPI as well (possible but adds a bit more maintenance overhead for us)  or need to get rid of the dependency.

**Comment by mseitzer** [comment]
I am open to replacing smart_settings with omegaconf, if we can keep backward compatibility by using smart_settings if it is installed (as discussed previously).

**Comment by luator** [comment]
Actually not yet resolved (sorry, wasn't aware that my comment on the smart-settings PR would close the issue here).
